name: Build cm5-io 6.1
on:
  workflow_dispatch:

jobs:
  query:
    runs-on: self-hosted
    outputs:
      linux: ${{ steps.query.outputs.linux }}
      u-boot: ${{ steps.query.outputs.u-boot }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Query available board configs
        id: query
        run: |
          echo "linux=$(./bsp json profile linux)" >> $GITHUB_OUTPUT
          echo "u-boot=$(./bsp json profile u-boot)" >> $GITHUB_OUTPUT
#  build_u-boot:
#    needs: query
#    runs-on: self-hosted
#    strategy:
#      matrix:
#        targets: [ u-boot ]
#        profiles: ${{fromJSON(needs.query.outputs.u-boot)}}
#    steps:
#      - name: Build
#        uses: Anthony-Andrews/bsp@main
#        with:
#          target: ${{ matrix.targets }}
#          edition: ${{ matrix.profiles }}
#          artifacts: true
  build_linux:
    needs: query
    runs-on: self-hosted
    strategy:
      matrix:
        targets: [linux]
        profiles: [rk2410] # this is radxa's codename for cm5-io reference boards
    steps:
      - name: Build
        uses: Anthony-Andrews/bsp@main
        with:
          target: ${{ matrix.targets }}
          edition: ${{ matrix.profiles }}
          artifacts: true

      - name: List output directory contents
        run: |
          pwd
          ls -la
          ls -la .output || ls -la output || echo "No output directory found"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
          name: linux_rk2410_build
          path: |
            .output/**
            output/**
