name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore

jobs:
  query:
    runs-on: ubuntu-latest
    outputs:
      forks: ${{ steps.query.outputs.forks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Query available board configs
        id: query
        run: |
          echo "::set-output name=forks::$(./bsp --json forks)"
  build:
    needs: query
    runs-on: ubuntu-latest
    strategy:
      matrix:
        forks: ${{fromJSON(needs.query.outputs.forks)}}
    steps:
      - name: Build
        uses: radxa-repo/bsp@main
        with:
          fork: ${{ matrix.forks }}